version: '3.8'

services:
  bot:
    build: .
    container_name: my_bot
    restart: unless-stopped
    volumes:
      - ./configs.json:/app/configs.json
      - ./datas.txt:/app/datas.txt
      - ./proxies.txt:/app/proxies.txt
    environment:
      - NODE_ENV=production
    stdin_open: true
    tty: true
